-
  name: 'await active resource'
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: GET
    headers:
      Content-Type: application/json
    status_code:
    - 200
    - 201
    - 202
    - 204
  register: result
  retries: 240
  delay: 1
  until: result.json['orchState'] == 'active'
  failed_when: result.json['orchState'] == 'failed'
