- import_tasks: get_resources_by_resourceTypeId.yml
- name: 'await active resource'
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources/{{ item.id }}'
    method: GET
    headers:
      Content-Type: application/json
    status_code:
    - 200
    - 201
    - 202
    - 204
  register: result
  retries: 60
  delay: 5
  until: result.json['orchState'] == 'active'
  loop: "{{ resources }}"
