-
  name: 'await active resource'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ bp_resource_id }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
    - 200
    - 201
    - 202
    - 204
  register: result
  retries: 240
  delay: 1
  until: result.json['orchState'] == 'active'
  failed_when: result.json['orchState'] == 'failed'
