- import_tasks: get_resources_by_resourceTypeId.yml
- name: 'await active resource'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ item.id }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
    - 200
    - 201
    - 202
    - 204
  register: result
  retries: 60
  delay: 5
  until: result.json['orchState'] == 'active'
  loop: "{{ bp_resources }}"
