- import_tasks: open_cache.yml # loads cache
- name: validate label has no spaces
  fail:
    msg: "Resource label must not contain spaces"
  when: label.find(" ") > 0
- name: validate label has no dashes
  fail:
    msg: "label must not contain dashes"
  when: label.find("-") > 0
- name: 'create resource'
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources'
    method: POST
    body:
      productId: "{{ productId }}"
      label: "{{ label }}"
      properties: "{{ properties }}"
    body_format: json
    headers:
      Content-Type: application/json
    status_code: 201
  register: result
- name: set the unkeyed_resource Fact
  set_fact:
    unkeyed_resource:
    - key: "{{ label }}"
      value: "{{ result.json['id'] }}"
- name: set the keyed_resource Fact
  set_fact:
    keyed_resource: "{{ unkeyed_resource | items2dict(key_name='key', value_name='value') }}"
- name: Update the keyed_resources Fact
  set_fact:
    keyed_resources: "{{ keyed_resources | combine(keyed_resource) }}"
    cacheable: true
- import_tasks: await_active.yml
  vars:
    resourceId: "{{ result.json['id'] }}"
