# This creates a domain based on domainType specification if the domain does not yet exist
# input:
#   domainType (this is converted to rpId)
#   title
#   description
#   accessUrl
#   address
#   properties
# Returns:
#   domainId
#   domain
- name: Clear the domainID Fact
  set_fact:
    domainId: ""
- name: Clear the domain Fact
  set_fact:
    domain: {}
- import_tasks: get_resourceProvider_by_domainType.yml # this sets rpId and resourceProvider var
- import_tasks: get_domains_by_domainType.yml # this sets domains var
- name: print WARNING
  debug:
    msg: "WARNING: domain already exists.  Not creating new domain"
    verbosity: 3
  when: (domains | length > 0)
- name: 'create domain'
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/domains'
    method: POST
    body:
      title: "{{ title }}"
      description: "{{ description }}"
      accessUrl: '{{ accessUrl }}'
      address: "{{ address }}"
      properties: "{{ properties }}"
      rpId: '{{ rpId }}'
    body_format: json
    headers:
      Content-Type: application/json
    status_code:
      - 200
      - 201
      - 202
      - 204
  register: result
  when: (domains | length == 0)
- name: set the domainId Fact
  set_fact:
    cacheable: true
    domainId: "{{ result.json['id'] }}"
- import_tasks: await_domain_onboard.yml
