- name: validate label has no spaces
  fail:
    msg: "Resource label must not contain spaces"
  when: label.find(" ") > 0
- name: validate label has no dashes
  fail:
    msg: "Resource label must not contain dashes"
  when: label.find("-") > 0
- name: validate productId is set
  fail:
    msg: "productId must be defined"
  when: productId is undefined
- name: 'create resource'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources'
    method: POST
    body:
      productId: "{{ productId }}"
      label: "{{ label }}"
      properties: "{{ properties }}"
    body_format: json
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code: 201
  register: result
- name: set the unkeyed_resource Fact
  set_fact:
    unkeyed_resource:
    - key: "{{ label }}"
      value: "{{ result.json['id'] }}"
- name: set the bp_keyed_resource Fact
  set_fact:
    bp_keyed_resource: "{{ unkeyed_resource | items2dict(key_name='key', value_name='value') }}"
- name: Update the bp_keyed_resources Fact
  set_fact:
    bp_keyed_resources: "{{ bp_keyed_resources | combine(bp_keyed_resource) }}"
    cacheable: true
- import_tasks: await_active.yml
  vars:
    bp_resource_id: "{{ result.json['id'] }}"
