- import_tasks: common/get_products.yml # this sets products and keyed_products var
- name: 'create resource'
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources'
    method: POST
    body:
      productId: "{{ keyed_products[resourceTypeId] }}"
      label: "{{ label }}"
      properties: "{{ properties }}"
    body_format: json
    headers:
      Content-Type: application/json
    status_code: 201
  register: result
- name: set the resourceId Fact
  set_fact:
    cacheable: true
    resourceId: "{{ result.json['id'] }}"
- name: set the resource Fact
  set_fact:
    cacheable: true
    resource: "{{ result.json }}"
# - name: set the specific resourceId Fact
#   set_fact:
#     cacheable: true
#     keyed_resources:
#     resourceId_"{{ label }}": "{{ result.json['id'] }}"
- import_tasks: common/await_active.yml
