- name: Is resource already deleted- {{ resourceId }}
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: GET
    status_code:
      - 200
      - 404
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  register: result
- name: Deleting resource {{ resourceId }}
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: DELETE
    status_code:
      - 204
      - 404
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  # until: ('status' in result) and (result.status == 204)
  retries: 120
  delay: 1
  register: result
- name: Verify delete resource {{ resourceId }}
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
      - 200
      - 404
  until: ('status' in result) and (result.status == 404)
  retries: 120
  delay: 1
  register: result
