- name: Clear the bp_resources Fact
  set_fact:
    cacheable: true
    bp_resources: []
- import_tasks: get_created_resources_by_resourceTypeId.yml
- name: Delete resource
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ item.id }}'
    method: DELETE
    status_code:
      - 204
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  with_items: "{{ bp_resources }}"
- name: Verify delete bp_resources
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ item.id }}'
    method: GET
    status_code:
      - 200
      - 404
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  with_items: "{{ bp_resources }}"
  until: result.failed is defined
  retries: 120
  delay: 1
  register: result
- name: Delete bp_resources
  debug:
    msg: "resources: {{ result }}"
    verbosity: 3
