- import_tasks: get_domains_by_domainType.yml # this sets domains var
- name: Delete domains
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/domains/{{ item.id }}'
    method: DELETE
    status_code:
      - 204
    validate_certs: no
    # headers:
    #   Cookie: "{{ fact_mdso_cookie }}"
    #   Authorization: "Bearer {{ fact_mdso_token }}"
  with_items: "{{ domains }}"
