- name: Delete resource
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: DELETE
    status_code:
      - 204
    validate_certs: no
    # headers:
    #   Cookie: "{{ fact_mdso_cookie }}"
    #   Authorization: "Bearer {{ fact_mdso_token }}"
- name: Verify delete resources
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: GET
    status_code:
      - 200
      - 404
    validate_certs: no
    # headers:
    #   Cookie: "{{ fact_mdso_cookie }}"
    #   Authorization: "Bearer {{ fact_mdso_token }}"
  until: result.failed is defined
  retries: 120
  delay: 1
  register: result
