- name: Deleting resource {{ resourceId }}
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: DELETE
    status_code:
      - 204
      - 404
    validate_certs: no
    # headers:
    #   Cookie: "{{ fact_mdso_cookie }}"
    #   Authorization: "Bearer {{ fact_mdso_token }}"
  until: ('status' in result) and (result.status == 204)
  retries: 120
  delay: 1
  register: result
- name: Verify delete resource {{ resourceId }}
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: GET
    validate_certs: no
    status_code:
      - 200
      - 404
    # headers:
    #   Cookie: "{{ fact_mdso_cookie }}"
    #   Authorization: "Bearer {{ fact_mdso_token }}"
  until: ('status' in result) and (result.status == 404)
  retries: 120
  delay: 1
  register: result
