- name: 'delete domain'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/domains/{{ bp_domain_id }}'
    method: DELETE
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 404
  register: result
- name: Verify delete domain
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/domains/{{ bp_domain_id }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
      - 200
      - 404
  until: ('status' in result) and (result.status == 404)
  retries: 120
  delay: 5
  register: result
