- import_tasks: get_domains_by_domainType.yml
- name: Delete bp_domains
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/domains/{{ item.id }}'
    method: DELETE
    status_code:
      - 204
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  with_items: "{{ bp_domains }}"
