- name: 'delete domain'
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/domains/{{ domainId }}'
    method: DELETE
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 404
  register: result
- name: Verify delete domain
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/domains/{{ domainId }}'
    method: GET
    status_code:
      - 200
      - 404
    validate_certs: no
    # headers:
    #   Cookie: "{{ fact_mdso_cookie }}"
    #   Authorization: "Bearer {{ fact_mdso_token }}"
  until: result.failed is defined
  retries: 120
  delay: 5
  register: result
