- name: 'get products'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/products?q=resourceTypeId:{{ resourceTypeId }}&includeInactive=true'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  register: result
- name: 'Fail when no products found'
  fail:
    msg: No products found for resourceTypeId {{ resourceTypeId }}
  when: result.json.total == 0
- name: Set tmp fact
  set_fact:
    cacheable: false
    tmp: "{{ result.json['items'] }}"
- name: Set individual facts
  set_fact:
    cacheable: true
    bp_keyed_products: "{{ tmp | items2dict(key_name='resourceTypeId', value_name='id') }}"
- name: print bp_keyed_products
  debug:
    msg: "bp_keyed_products: {{ bp_keyed_products }}"
    verbosity: 3
