- name: Get ResourceType {{ resourceTypeId }}
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resource-types/{{ resourceTypeId }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  register: result
