- name: Get ResourceType {{ resourceType }}
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resource-types/{{ resourceType }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  register: result
- name: Set the resourceType Fact
  set_fact:
    cacheable: true
    resourceType: "{{ result.json }}"
- name: print resourceType
  debug:
    msg: "resourceType: {{ resourceType }}"
    verbosity: 3
