- name: 'check for existing domain'
  uri:
    url: '{{mdso.BP_SERVER}}/bpocore/market/api/v1/domains?q=domainType:urn:ciena:bp:domain:{{domainType}}'
    method: GET
    status_code:
      - 200
  register: result
- name: Set the domains Fact
  set_fact:
    cacheable: true
    domains: "{{ result.json['items'] }}"
- name: print domains
  debug:
    msg: "domains: {{ domains }}"
    verbosity: 3
