- name: 'get products'
  uri:
    url: '{{bp_integration_tests_server}}/bpocore/market/api/v1/products?q=resourceTypeId:{{ resourceType }}&includeInactive=true'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  register: result
- name: 'Fail when no products found'
  fail:
    msg: No products found for ResourceType {{ resourceType }}
  when: result.json.total == 0
- name: Set the products Fact
  set_fact:
    cacheable: true
    products: "{{ result.json['items'] }}"
- name: print products
  debug:
    msg: "products: {{ products }}"
    verbosity: 3
- name: Set individual facts
  set_fact:
    cacheable: true
    keyed_products: "{{ products | items2dict(key_name='resourceTypeId', value_name='id') }}"
- name: print keyed_products
  debug:
    msg: "keyed_products: {{ keyed_products }}"
    verbosity: 3
