- name:
  set_fact:
    cacheable: true
    query: "{{ lookup('template', './templates/get_resource_by_filters.j2') }}"
- name: print query
  debug:
    msg: "query: {{ query }}"
    verbosity: 3
- name: 'get resources'
  uri:
    url: "{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources?resourceTypeId={{ resourceTypeId }}{{ query }}"
    method: GET
    validate_certs: no
  register: result
- name: Set the resources Fact
  set_fact:
    cacheable: true
    resources: "{{ result.json['items'] }}"
- name: print resources
  debug:
    msg: "resources: {{ resources }}"
    verbosity: 3
- name: Set the resource Fact
  set_fact:
    cacheable: true
    resource: "{{ resources[0] }}"
- name: print resource
  debug:
    msg: "resource: {{ resource }}"
    verbosity: 3
