- name: Get Resource Providers
  block:
  - name: 'get resource-providers'
    uri:
      url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resource-providers?q=domainType:{{ domainType }}'
      method: GET
      validate_certs: no
      headers:
        Authorization: "Bearer {{ bp_integration_tests_token }}"
    register: result
  - name: validate RP's
    assert:
        that:
          - result.json['items'] is defined
          - (result.json['items'] | length) > 0
        success_msg: validate RP's
        fail_msg: resource provider {{ domainType }} not found
- name: Set the resourceProviders Fact
  set_fact:
    tmp: "{{ result.json['items'] }}"
- name: Set the resourceProviders Fact
  set_fact:
    cacheable: true
    bp_resourceProvider_id: "{{ result.json['items'][0]['id'] }}"
- name: print resourceProviders
  debug:
    msg: "resourceProviders: {{ tmp }}"
    verbosity: 3
- name: Set bp_keyed_resourceProviders fact
  set_fact:
    cacheable: true
    bp_keyed_resourceProviders: "{{ tmp | items2dict(key_name='domainType', value_name='id') }}"
- name: print bp_keyed_resourceProviders
  debug:
    msg: "bp_keyed_resourceProviders: {{ bp_keyed_resourceProviders }}"
    verbosity: 3
