- name: 'get products'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/domains/{{ bp_domain_id }}/products?includeInactive=true'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  register: result
- name: Set individual facts
  set_fact:
    tmp: "{{ result.json['items'] }}"
    cacheable: false
- name: Set individual facts
  set_fact:
    cacheable: true
    bp_keyed_products: "{{ tmp | items2dict(key_name='resourceTypeId', value_name='id') }}"
- name: print bp_keyed_products
  debug:
    msg: "bp_keyed_products: {{ bp_keyed_products }}"
    verbosity: 3
