- name: Get Resource Providers
  block:
  - name: 'get resource-providers'
    uri:
      url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resource-providers'
      method: GET
      validate_certs: no
      headers:
        Authorization: "Bearer {{ bp_integration_tests_token }}"
    register: result
    failed_when: (result.json['items'] | length) == 0
  rescue:
  - name: Fail when Resource Provider not found
    fail:
      msg: No Resource Providers exist.
- name: Set bp_keyed_resourceProviders fact
  vars:
    tmp: "{{ result.json['items'] }}"
  set_fact:
    cacheable: true
    bp_keyed_resourceProviders: "{{ tmp | items2dict(key_name='domainType', value_name='id') }}"
- name: print bp_keyed_resourceProviders
  debug:
    msg: "bp_keyed_resourceProviders: {{ bp_keyed_resourceProviders }}"
    verbosity: 3
