- name: 'get resources'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources?resourceTypeId={{ resourceTypeId }}&q=discovered:false'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
  register: result
- name: Set the bp_resources Fact
  set_fact:
    cacheable: true
    bp_resources: "{{ result.json['items'] }}"
- name: print bp_resources
  debug:
    msg: "bp_resources: {{ bp_resources }}"
    verbosity: 3
