- name: 'check for existing domain'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/domains'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
      - 200
  register: result
- name: Set the bp_domains Fact
  set_fact:
    cacheable: false
    bp_domains: "{{ result.json['items'] }}"
- name: print bp_domains
  debug:
    msg: "domains: {{ bp_domains }}"
    verbosity: 3
- name: Set individual facts
  set_fact:
    tmp: "{{ result.json['items'] }}"
    cacheable: false
- name: Set individual facts
  set_fact:
    cacheable: false
    tmp_bp_keyed_domains: "{{ tmp | items2dict(key_name='title', value_name='id') }}"
- name: Combine the domains fact
  set_fact:
    cacheable: true
    bp_keyed_domains: "{{ bp_keyed_domains | combine(tmp_bp_keyed_domains) }}"
- name: print bp_keyed_domains
  debug:
    msg: "bp_keyed_domains: {{ bp_keyed_domains }}"
    verbosity: 3
