- name: 'get domain'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/domains?q=domainType:{{ domainType }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
      - 200
  register: result
- name: Set the bp_domain_id Fact
  set_fact:
    cacheable: true
    bp_domain_id: "{{ result.json['items'][0]['id'] }}"
  when: (result.json['items'] | length) > 0
- name: Set the bp_domain Fact
  set_fact:
    cacheable: true
    bp_domain: "{{ result.json['items'][0] }}"
  when: (result.json['items'] | length) > 0
