- name: 'check for existing domain'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/domains?q=domainType:urn:ciena:bp:domain:{{ domainType }}'
    method: GET
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
      - 200
  register: result
- name: Set the bp_domains Fact
  set_fact:
    cacheable: true
    bp_domains: "{{ result.json['items'] }}"
- name: print bp_domains
  debug:
    msg: "domains: {{ bp_domains }}"
    verbosity: 3
