- name: 'load cache'
  include_vars:
    file: localhost
    name: blueplanet_cache
  ignore_errors: true
- name: Set the root keyed_domains Fact
  set_fact:
    keyed_domains: []
    cacheable: true
  when: blueplanet_cache.keyed_resources is not defined
- name: Set the root keyed_resources Fact
  set_fact:
    keyed_resources: []
    cacheable: true
  when: blueplanet_cache.keyed_resources is not defined

- name: Merge the root keyed_domains fact
  set_fact:
    keyed_domains: "{{ blueplanet_cache.keyed_domains }}"
  when: blueplanet_cache.keyed_domains is defined
- name: Merge the root keyed_resources fact
  set_fact:
    keyed_resources: "{{ blueplanet_cache.keyed_resources }}"
  when: blueplanet_cache.keyed_resources is defined
