- name: 'patch resource'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: PATCH
    body:
      properties: "{{ properties }}"
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code:
      - 200
      - 201
  register: result
- import_tasks: await_active.yml
