- name: 'get resource by label'
  import_tasks: get_resource_0_by_filters.yml
  vars:
    - resourceTypeId: "{{ resourceTypeId }}"
    - p_params:
        label: "{{ label }}"
- name: 'patch resource'
  uri:
    url: '{{ bp_integration_tests_server }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: PATCH
    body:
      properties: "{{ properties }}"
    body_format: json
    validate_certs: no
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ bp_integration_tests_token }}"
    status_code: 201
  register: result
- import_tasks: await_active.yml
