- name: 'patch resource'
  uri:
    url: '{{ mdso.BP_SERVER }}/bpocore/market/api/v1/resources/{{ resourceId }}'
    method: PATCH
    body:
      properties: "{{ properties }}"
    body_format: json
    headers:
      Content-Type: application/json
    status_code: 201
  register: result
- import_tasks: await_active.yml
